### PR TITLE
Add GitHub action "Register Package"

### PR DESCRIPTION
**Pull request by singularitti**
This file is generated by [PkgTemplates.jl](https://invenia.github.io/PkgTemplates.jl/dev/user/#PkgTemplates.RegisterAction).
This action can make releasing a new version very easy:
image
Just click "Run Workflow", type your new version and click confirm, done! A new version will be registered on Julia's `General` registry.

### CODE REVIEW

**Comment by Eben60** [comment]
Thank you @singularitti - just I consider the package as not yet ready for registration. Actually - I don't know, does anybody really need it? Do **you** have any real applications? I don't, but if the package is really being used, I'd check my TODOs when I have time, finish it and register then.

**Comment by singularitti** [comment]
There is a similar package called https://github.com/tmattick/ChemicalFormula.jl. I wish to know what is different between your implementations.

**Comment by Eben60** [comment]
See https://github.com/tmattick/ChemicalFormula.jl/issues/3#issuecomment-1361261057 ;)

You didn't answer my question, did you?

**Comment by singularitti** [comment]
No. I did not see the link. So this repository is not going to be maintained, is that right?

**Comment by Eben60** [comment]
That is not exactly right. May I refer you to my first reply and especially to the question I've asked you. What is your application, what do you need? Are your needs covered by that another package? If not, what specifically? 

See also https://github.com/Eben60/ChemFormulae.jl/issues/1

**Pull request closed without merging**
